---
services:
  openwebui:
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434

  mcpo:
    volumes:
      - type: bind
        source: ./mcp-configs/portable.json
        target: /app/config.json
        read_only: true
