---
services:
  openwebui:
    ports:
      - "8080:8080"
    environment:
      # TODO: This is my WSL IP address
      - OLLAMA_BASE_URL=http://192.168.1.137:11434

  mcpo:
    volumes:
      - type: bind
        source: ./mcp-configs/home.json
        target: /app/config.json
        read_only: true
