---
services:
  openwebui:
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      # - ENABLE_CHANNELS=false
      # - WEBHOOK_URL=http://localhost
      # TODO: check it: tとfでの違いを見る
      - ENABLE_DIRECT_CONNECTIONS=true
      - USER_PERMISSIONS_FEATURES_DIRECT_TOOL_SERVERS=false

  mcpo:
    volumes:
      - type: bind
        source: ./mcp-configs/company.json
        target: /app/config.json
        read_only: true
